- name: Create validator testnet dir
  file:
    path: "{{validator_host_dir}}/custom_testnet_config"
    state: directory

- name: Configure validator node custom testnet
  copy:
    src: "{{custom_testnet_lighthouse_dir}}/"
    dest: "{{validator_host_dir}}/custom_testnet_config"
