- name: Create beacon custom testnet dir
  file:
    path: "{{beacon_host_dir}}/custom_testnet_config"
    state: directory

- name: Configure beacon node custom testnet
  copy:
    src: "{{custom_testnet_lodestar_config}}"
    dest: "{{beacon_host_dir}}/custom_testnet_config/lodestar_config.yaml"
