- name: Eth2stats
  docker_container:
    name: "{{ eth2stats_container_name }}"
    state: started
    image: "{{ eth2stats_image_name }}"
    restart_policy: unless-stopped
    network_mode: host
    restart: "{{ eth2stats_require_restart | default(false) }}"
    log_options: "{{ common_log_options }}"
    volumes:
      - "{{eth2stats_host_dir}}:/data"
    command: >
      run
      --eth2stats.node-name="{{ eth2stats_display_name }}"
      --data.folder="/data"
      --eth2stats.addr="{{ eth2stats_addr }}" --eth2stats.tls=true
      --beacon.type="{{ eth2stats_beacon_type }}"
      --beacon.addr="{{ eth2stats_api_addr }}"
      {% if eth2stats_metrics_url is defined %}
      --beacon.metrics-addr="{{ eth2stats_metrics_url }}"
      {% endif %}
