bootnode_container_name: bootnode
bootnode_memory: 1000m
bootnode_image_name: protolambda/eth2-bootnode:latest

bootnode_port: 5000
# TODO: change this
bootnode_ip: 1.2.3.4
# 32 bytes, hex encoded, no 0x.
# E.g. "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
bootnode_p2p_priv_key: change me

bootnode_fork_version: "0x00000000"

bootnode_start_args: >
  {% if (other_bootnodes is defined) and other_bootnodes %}
  --bootnodes="{{ other_bootnodes | join(',') }}"
  {% endif %}
  --color=false
  --enr-ip="{{bootnode_ip}}"
  --enr-udp="{{bootnode_port}}"
  --fork-version="{{bootnode_fork_version}}"
  --level=debug
  --listen-ip=0.0.0.0
  --listen-udp="{{bootnode_port}}"
  --node-db="/data/localnode.db"
  --priv="{{bootnode_p2p_priv_key}}"
