beacon_image_name: pegasyseng/teku:develop

validators_config_file: "validators_config.yml"

beacon_env:
  JAVA_OPTS: "-Xmx3500m"
  LOG4J_CONFIGURATION_FILE: "{{beacon_container_dir}}/log_config.xml"

beacon_memory: 3600M
beacon_kernel_memory: 3700M

validator_memory: No validator container yet

# Debug logging spams a ton of http data every eth2stats call (every second).
beacon_start_args: >
  {% if testnet_type == 'custom' %}
  --network="{{beacon_container_dir}}/custom_testnet_config/teku_config.yaml"
  --eth1-deposit-contract-address="{{deposit_contract_address}}"
  --p2p-snappy-enabled=true
  {% elif testnet_type == 'altona' %}
  --network=altona
  {% elif testnet_type == 'medalla' %}
  --network=medalla
  {% endif %}
  --data-storage-mode=PRUNE
  --data-path="{{beacon_container_dir}}"
  --p2p-advertised-ip={{public_ip_address}}
  --p2p-advertised-port={{beacon_udp_port}}
  --p2p-port={{beacon_tcp_port}}
  --p2p-discovery-enabled=true
  --p2p-peer-lower-bound={{lo_peer_count}}
  --p2p-peer-upper-bound={{hi_peer_count}}
  --log-destination=DEFAULT_BOTH
  --log-file="{{beacon_container_dir}}/log_outputs"
  --eth1-endpoint={{eth1_endpoint.http}}
  --rest-api-enabled=true --rest-api-interface=0.0.0.0 --rest-api-port={{beacon_rpc_port}}
  --metrics-enabled --metrics-interface=0.0.0.0 --metrics-port={{beacon_metrics_port}}
  --metrics-host-allowlist="*"
  --rest-api-host-allowlist="*"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --p2p-discovery-bootnodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  {% if validator_enabled %}
  --validators-graffiti="{{ validator_graffiti }}"
  --config-file="{{beacon_container_dir}}/{{validators_config_file}}"
  {% endif %}

keystores_container_dir: "{{beacon_container_dir}}/keys"
secrets_container_dir: "{{beacon_container_dir}}/secrets"

keystores_host_dir: "{{beacon_host_dir}}/keys"
secrets_host_dir: "{{beacon_host_dir}}/secrets"

validator_config_host_path: "{{ beacon_host_dir }}/{{validators_config_file}}"
