beacon_image_name: sigp/lighthouse:latest
beacon_start_args: >
  lighthouse
  --debug-level="{{ beacon_log_level | lower }}"
  --datadir="{{beacon_container_dir}}"
  {% if testnet_type == 'custom' %}
  --testnet-dir="{{beacon_container_dir}}/custom_testnet_config"
  {% endif %}
  bn
  --graffiti="{{validator_graffiti}}"
  --disable-enr-auto-update=true
  --enr-address={{public_ip_address}}
  --enr-tcp-port={{beacon_tcp_port}} --enr-udp-port={{beacon_udp_port}}
  --port={{beacon_tcp_port}} --discovery-port={{beacon_udp_port}}
  --target-peers={{hi_peer_count}}
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --boot-nodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --eth1 --eth1-endpoint={{eth1_endpoints.goerli_prysm.http}}
  --http --http-address=0.0.0.0 --http-port={{beacon_rpc_port}}
