beacon_image_name: protolambda/nim_beacon_node:latest
beacon_start_args: >
  beacon_node
  --network=altona
  --data-dir="{{beacon_container_dir}}"
  --web3-url={{eth1_endpoint.ws}}
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --bootstrap-node="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --udp-port={{beacon_udp_port}}
  --tcp-port={{beacon_tcp_port}}
  --listen-address=0.0.0.0
  --graffiti="{{ validator_graffiti }}"
  --nat="extip:{{public_ip_address}}"
  --log-level="{{ beacon_log_level | upper }}"
  --rpc --rpc-port={{beacon_rpc_port}} --rpc-address=0.0.0.0
  --metrics --metrics-port={{beacon_metrics_port}} --metrics-address=0.0.0.0
  {% if validator_enabled and (not has_validator_client) %}
    --validators-dir="{{keystores_container_dir}}"
    --secrets-dir="{{secrets_container_dir}}"
  {% else %}
    --validators-dir="{{beacon_container_dir}}/no_bn_keys"
    --secrets-dir="{{beacon_container_dir}}/no_bn_secrets"
  {% endif %}
