keystores_container_dir: "{{validator_container_dir}}/keys"
secrets_container_dir: "{{validator_container_dir}}/secrets"

keystores_host_dir: "{{validator_host_dir}}/keys"
secrets_host_dir: "{{validator_host_dir}}/secrets"

validator_memory: 400m

validator_image_name: >
  {% if testnet_type == 'custom' %}
  {% if eth2_network_name == 'attacknet_beta' %}
  protolambda/nimbus:attacknet
  {% endif %}
  {% elif testnet_type == 'altona' %}
  protolambda/nimbus:altona
  {% elif testnet_type == 'medalla' %}
  protolambda/nimbus:medalla
  {% endif %}

validator_start_args: >
  validator_client
  --log-level="INFO"
  --data-dir="{{validator_container_dir}}"
  --non-interactive=true
  --graffiti="{{ validator_graffiti }}"
  --rpc-port={{beacon_rpc_port}}
  --rpc-address=127.0.0.1
  --validators-dir="{{keystores_container_dir}}"
  --secrets-dir="{{secrets_container_dir}}"
