beacon_image_name: gcr.io/prysmaticlabs/prysm/beacon-chain
beacon_start_args: >
  --datadir="{{beacon_container_dir}}"
  {% if testnet_type == 'custom' %}
  --chain-config-file="{{beacon_container_dir}}/config/prysm_config.yaml"
  --deposit-contract="{{deposit_contract_addr}}"
  --contract-deployment-block="{{deposit_contract_deploy_block_nr}}"
  --custom-genesis-delay="{{genesis_delay}}"
  {% elif testnet_type == 'altona' %}
  --altona
  {% endif %}
  --p2p-host-ip={{public_ip_address}}
  --p2p-max-peers={{hi_peer_count}}
  --p2p-udp-port={{beacon_udp_port}} --p2p-tcp-port={{beacon_tcp_port}}
  --monitoring-host=0.0.0.0 --monitoring-port={{beacon_metrics_port}}
  --rpc-host=0.0.0.0 --rpc-port={{beacon_grpc_port}}
  --grpc-gateway-host=0.0.0.0
  --grpc-gateway-port={{beacon_rpc_port}}
  --verbosity=debug
  --enable-debug-rpc-endpoints
  --min-sync-peers 1
  --bootstrap-node="enr:-KG4QLkU_qJgdh-DhT5HtONGvuqwbbW99piCe27Bpk8oO_hvC0qEYgOSpmVfZ-8iJgW71HO23ajEFCNOCvEaqpcIXiUDhGV0aDKQ_co5sAAAASH__________4JpZIJ2NIJpcIQDE_KiiXNlY3AyNTZrMaEDbBoq33b6SAUh96EJZWNYOqYwjm78pVviDreLfK-aeUKDdGNwgiMog3VkcIIjKA"
