validator_memory: 400m

validator_image_name: gcr.io/prysmaticlabs/prysm/validator
validator_start_args: >
  --datadir="/data"
  {% if testnet_type == 'custom' %}
  --chain-config-file="{{validator_container_dir}}/custom_testnet_config/prysm_config.yaml"
  {% elif testnet_type == 'altona' %}
  --altona
  {% endif %}
  --beacon-rpc-provider=localhost:{{beacon_grpc_port}}
  --graffiti="{{ validator_graffiti }}"
  --monitoring-host=0.0.0.0 --monitoring-port={{validator_metrics_port}}
  --password=""
  --keymanager=wallet
  --keymanageropts={{ validator_container_dir }}/keymanager_opts.json
