keystores_relative_dir: "keystores"
secrets_relative_dir: "secrets"
validators_db_relative_dir: "validators"

keystores_host_dir: "{{validator_host_dir}}/{{keystores_relative_dir}}"
secrets_host_dir: "{{validator_host_dir}}/{{secrets_relative_dir}}"
validators_db_host_dir: "{{validator_host_dir}}/{{validators_db_relative_dir}}"

validator_memory: 400m

validator_image_name: chainsafe/lodestar:latest
validator_start_args: >
  validator
  {% if testnet_type == 'custom' %}
  --config="{{validator_container_dir}}/custom_testnet_config/lodestar_config.yml"
  {% elif testnet_type == 'medalla' %}
  --testnet=medalla
  {% elif testnet_type == 'altona' %}
  --testnet=altona
  {% endif %}
  --rootDir="{{validator_container_dir}}"
  --keystoresDir="{{keystores_relative_dir}}"
  --secretsDir="{{secrets_relative_dir}}"
  --validatorsDbDir="{{validators_db_relative_dir}}"
  --graffiti="{{validator_graffiti}}"
  --server=http://localhost:{{beacon_rpc_port}}/
