- name: Prepare for lighthouse v0.3 update
  hosts: eth2client_lighthouse
  gather_facts: false
  tasks:
    - name: Stop beacon node
      shell: docker stop beacon
    - name: Stop validator client
      shell: docker stop validator
    - name: Stop eth2stats-client
      shell: docker stop eth2stats-client
    - name: Rm beacon node
      shell: docker rm beacon
    - name: Rm validator client
      shell: docker rm validator
    - name: Rm eth2stats-client
      shell: docker rm eth2stats-client
    - name: Wipe beacon data
      become: true
      shell: rm -rf beacon
    - name: Wipe validator data
      become: true
      shell: rm -rf validator
    - name: Pull eth2stats update to be sure
      shell: docker pull alethio/eth2stats-client:latest
