- name: Reset beacon
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Stop beacon node
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: stop-beacon
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
    - name: Wipe beacon containers
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: wipe-beacon
      loop: ['{{ eth2client_name }}']
    - name: Start beacon node
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-beacon
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
