---
- name: Restart nodes
  hosts:
    - beacon_node
  roles:
    - eth2client
  gather_facts: true
  vars:
    beacon_require_restart: true
    validator_require_restart: true
    eth2stats_require_restart: true
  tasks:
    - name: Start validator client
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-validator
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
      when: validator_enabled
    - name: Start beacon node
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-beacon
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
    - name: Start eth2stats
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: start-eth2stats
      when: eth2stats_enabled
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
