- name: Assign validators
  # each validator client is running on a machine with a beacon node, change this later.
  hosts: beacon_node
  gather_facts: false
  vars:
    restart_validator_afterwards: false  # Do not start validators yet
  tasks:
    - name: Deploy validator keys
      include_role:
        name: eth2client
        defaults_from: '{{eth2client_name}}'
        tasks_from: assign-validators
      when: validator_enabled

- name: Start beacon nodes (and optional in-beacon validators)
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Start beacon containers
      include_role:
        name: eth2client
        defaults_from: '{{eth2client_name}}'
        tasks_from: start-beacon

- name: Start validator clients
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Start validator containers
      include_role:
        name: eth2client
        defaults_from: '{{eth2client_name}}'
        tasks_from: start-validator
      when: validator_enabled

- name: Start eth2stats
  hosts: beacon_node
  gather_facts: false
  tasks:
    - name: Start eth2stats containers
      include_role:
        name: eth2client
        defaults_from: '{{eth2client_name}}'
        tasks_from: start-eth2stats
      when: eth2stats_enabled
