---
- name: Stop nodes
  hosts:
    - beacon_node
  gather_facts: false
  tasks:
    - name: Stop validator client
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: stop-validator
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
      when: validator_enabled
    - name: Stop beacon node
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: stop-beacon
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
    - name: Stop eth2stats
      include_role:
        name: eth2client
        defaults_from: '{{item}}'
        tasks_from: stop-eth2stats
      when: eth2stats_enabled
      loop:
        - '{{ eth2client_name }}'  # needs to be dynamic
