---
- name: Stop nodes
  hosts:
    - beacon_node
  roles:
    - eth2client
  gather_facts: false
  tasks:
    - name: Stop validator client
      include_tasks: roles/eth2client/tasks/stop-validator.yml
      when: validator_enabled
    - name: Stop beacon node
      include_tasks: roles/eth2client/tasks/stop-beacon.yml
    - name: Stop eth2stats
      include_tasks: roles/eth2client/tasks/stop-eth2stats.yml
      when: eth2stats_enabled
